name: "env-from-aws-ssm-list"
description: "Pass SSM Parameter Store values from a file to dotenv file"
author: "enuelx"
inputs:
  inputFilename:
    description: "Filename received as parameter or .env.map by default"
  outputFilename:
    description: "Filename received as parameter or .env by default"
runs:
  using: "node16"
  main: "dist/index.js"
